inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - Gemfile
    - bin/*

Metrics/BlockNesting:
  Max: 5
  # default is 4

Metrics/CyclomaticComplexity:
  Max: 9
  # default is 6

Metrics/PerceivedComplexity:
  Max: 12
  # default is 7
